
 -- SELECT <조회 컬럼명> FROM <테이블명>

SELECT 
	e.EMPNO
	, e.ENAME
	, d.DNAME
	, d.LOC
FROM EMP e
INNER JOIN DEPT d ON e.DEPTNO  = d.DEPTNO ;

SELECT 
*
FROM emp
ORDER BY SAL ASC; -- DESC :: 내림차순
-- WHERE ENAME = 'ALLEN';

SELECT * FROM BONUS ;
SELECT * FROM DEPT  ;
SELECT * FROM EMP  ;
SELECT * FROM SALGRADE ; 

SELECT 
  EMPNO,
  ENAME,
  SAL,
  DEPTNO
FROM EMP ;

SELECT *
FROM EMP e 
WHERE SAL >= 3000 ;

SELECT 
FROM EMP e 
WHERE SAL >= 3000 AND SAL <= 5000 ;


SELECT 
 EMPNO,
 ENAME,
 SAL
FROM EMP e 
WHERE (SAL >=3000 or SAL < 1500) AND ENAME LIKE '%L%' ;

SELECT 
 EMPNO,
 ENAME,
 SAL
FROM EMP e 
WHERE (SAL >=3000 or SAL < 1500) ORDER BY SAL DESC ; 

SELECT 
 EMPNO,
 ENAME,
 SAL,
 COMM 
FROM EMP e 
WHERE COMM  IS NOT NULL --IS NULL  

SELECT 
 EMPNO,
 ENAME,
 SAL,
 COMM 
FROM EMP e
WHERE EMPNO IN (7369,7499,7521,7566);

SELECT  ENAME, UPPER(ENAME), LOWER(ENAME)
FROM EMP e ;

SELECT JOB, SUBSTR(JOB,1,2) ,SUBSTR(JOB,3,2), SUBSTR(JOB,5) 
FROM EMP e ;


-- 문제 -- 
SELECT ENAME,
 RPAD(SUBSTR(ENAME,1,LENGTH(ENAME) -2),LENGTH(ename),'*') AS SUBSTR
FROM EMP e ;
----

SELECT 
NVL(COMM, 2)
FROM EMP e ;

SELECT 
count(*),
sum(sal),
DEPTNO
FROM EMP e 
GROUP BY DEPTNO ;

CREATE TABLE emp_detail
(
   tel varchar2(20),
   child number(2),
   age number(3),
   empno number(4)
      -- 제약조건
      CONSTRAINT emp_detail_EMP_EMPNO_fk -- 제약조건명
         REFERENCES EMP -- 참조테이블과 참조할 컬럼(컬럼을 명시하지않으면 자동으로 pk를 참조)
            ON DELETE cascade
)

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01012345678', 0, 20, 7369);
-- 전화번호 안겹치게, 자녀수 0 또는 1, 나이 알아서
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01098765432', 3, 45, 7499);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01023568978', 2, 30, 7521);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01012554688', 4, 51, 7566);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01047589658', 1, 28, 7654);
SELECT * FROM EMP e ;